accordproject/template-playground

src/AgreementData.tsx, src/ConcertoEditor.tsx, src/JSONEditor.tsx, src/TemplateModel.tsx
- Created `JSONEditor` and `ConcertoEditor` components with appropriate syntax highlighting
=> feat(editor): Added syntax highlighting for concerto and json editors

index.html
This PR fixes #31 
Playground currently displays an inaccurate favicon. Currently it showcases the logo of Vite. This may cause confusion among users, as it misrepresents the platform's identity.Instead of displaying vite icon the Accord Project icon should be displayed
=> fixed inappropriate favicon to accordproject icon

.github/workflows/build-and-publish.yml, .github/workflows/pr-check.yml
run build step in ci pipeline for PR
=> chore(workflow): run build step in ci pipeline for PR

src/SampleDropdown.tsx
=> fix(templates): render sample template name

package-lock.json, package.json
Fixed failed production pipeline issue. Build error caused by the missing `cross-env` package. The error preventing the build process from recognizing environment variables. Necessary package for ensuring successful builds and improving cross-platform compatibility.
=> chore(CI): fix build and deployment issues

src/AgreementHtml.tsx, src/App.tsx, src/SampleDropdown.tsx, src/components/Footer.tsx, src/index.css
- Contents of playground base always be at the bottom of the screen. Even if the content is still loading.
- Auto scrolling to the template output section so that the footer and related components does not overflow.
- Drilled load state through all template sample render components.
- Templates preview output new border redesign
- Issue #72
=> fix(templates): template whitespace, drilled load and auto scroll on template output

src/ConcertoEditor.tsx, src/JSONEditor.tsx, src/MarkdownEditor.tsx
- <ONE>Addressed an issue where the white-spacing in the Monaco editor was not consistent, it led to disturbance in layout of the template block.
=> Fix(GUI): white-spacing in monaco editor

src/ConcertoEditor.tsx
Added Syntax Highlighting for concerto editor
Preview:
=> feat(ConcertoEditor): Added Syntax Highlighting

package-lock.json, package.json, src/AgreementData.tsx, src/AgreementHtml.tsx, src/App.tsx, src/ConcertoEditor.tsx, src/Errors.tsx, src/FullScreenModal.tsx, src/JSONEditor.tsx, src/MarkdownEditor.tsx, src/TemplateMarkdown.tsx, src/TemplateModel.tsx, src/components/UseShare.tsx, src/main.tsx, src/store.ts, utils/compression/compression.ts
- Serialize and encode template data into a URL-friendly format using `lz-string`.
- Provide functionality to generate shareable links with encoded template data.
- Decode and load template data from the URL when accessed via a shared link.
- **Compression Utility Functions:**
- `compress`: Serializes and compresses template data.
- `decompress`: Decodes and deserializes compressed data from the URL.
- **Zustand Store Updates:** `generateShareableLink` logic function.
- Issue #48 #47
=> feat: generate shareable links implementation, lz-string compression and encoded template data in URLs

src/components/Navbar.tsx
This pull request addresses issue #84 , which highlights the problem of the logo appearing stretched on mobile devices and in the Safari browser. The issue was caused by browser-defined CSS, which has now been fixed. The logo will maintain its aspect ratio and display correctly on all devices and browsers, including mobile devices and Safari.
- <ONE>Ensured the logo's dimensions are set to auto to maintain its aspect ratio.
- <TWO>Used CSS media queries to adjust the logo size for different screen sizes.
- <THREE>Tested and fixed Safari-specific CSS issues.
- Issue #84 #82 
- Pull Request #86
=> fix(GUI): Stretched Logo on Safari Browser

src/store/store.ts, src/tests/store/generateSharebleLink.test.tsx
- Fixed issue where `agreementHtml` was not showing the preview on the shared generated link.
- Ensured that `agreementHtml` is included in the state when generating the shareable link.
- The fix involves mocking the `rebuild` function to ensure `agreementHtml` is correctly set for testing.
- **prior**
- **fix**
=> fix(sharable): agreementData preview screen on shared generated-link bug fixed

package-lock.json, src/editors/editorsContainer/AgreementData.tsx, src/editors/editorsContainer/TemplateMarkdown.tsx, src/editors/editorsContainer/TemplateModel.tsx, src/store/store.ts
The Monaco editor were experiencing cursor jumping issues and edit lost when updating state using Zustand. The cursor would jump to the top or bottom of the editor, causing a poor user experience. This issue was identified as a result of state updates causing unnecessary re-renders.
- <ONE> To resolve this, I implemented immediate state management for the editor components, separating the state used for rendering the editor (editorValue, editorModelCto, and editorAgreementData) from the state used for processing updates . By updating the rendering state immediately and debouncing the processing state updates, I was able to stop the unnecessary re-rendering that made the cursor jump around all over the place.
- <ONE> Replaced direct state updates with immediate state updates in all the …
=> fix(Editor) Cursor Inconsistency and edit lost fix in monaco editor

vite.config.ts
This pull request optimizes the build performance of the project by addressing the Vite warning regarding mixed ESM and CJS modules. 
- Added the package `@accordproject/template-engine` to `optimizeDeps.needsInterop` in `vite.config.js` to improve cold start performance.
- This change aims to enhance the build performance and reduce the likelihood of encountering mixed module issues during development.
=> fix(optimizeDeps): added @accordproject/template-engine to vite optimizeDeps to speed up cold start

package-lock.json, src/components/SampleDropdown.tsx, src/store/store.ts
- <ONE>Optimized dropdown by using shallow comparison from zustand/shallow to prevent redundant re-renders.
- <TWO>Used useMemo for dropdown items to prevent unnecessary recalculations.
- <THREE>Used useCallback for handleMenuClick to avoid function recreation on each render.
- <FOUR>Wrapped the component with memo to prevent unnecessary re-renders.
- <ONE>Avoided redundant calls to get() within rebuild to improve efficiency.
- <TWO>Ensured debounce optimization (rebuildDeBounce) remains effective.
- Issue #123 
- Pull Request #122
=> perf(SampleDropdown & Store): Memoization & Redundancy fix with Readability & Modularity 

src/editors/MarkdownEditor.tsx
This PR fixes the Monaco Editor's theme issue while toggling dark mode which was mistakenly removed in my PR #128 to ensure consistency with the overall theme I have restored the theme logic again. Apologies for the mistake.
- <ONE> Initiated the `useEffect` block to trigger the theme for the Monaco Editor
- Issue #<NUMBER>
- Pull Request #139
=> Fix(Editor Theme): Monaco Editor Dark Mode theme Fixed

package-lock.json, package.json, src/AgreementHtml.tsx, src/App.tsx, src/components/FullScreenModal.tsx, src/components/Navbar.tsx, src/components/Tour.ts, src/styles/components/ToggleDarkMode.ts, src/tests/components/Navbar.test.tsx
This PR addresses layout shift issues affecting the DarkToggle Button and Full-Screen Modal, ensuring a smoother and more consistent UI experience.
- Fixed unintended layout shift on Full screen modal while on start guide tour.
- Adjusted positioning of the Darkmode button to prevent UI flickering and unnecessary clicks.
=> Fix(Layout Shift Fix) - Resolved Layout Issues on DarkMode Toggle Button and Full-Screen Modal

src/App.tsx, src/components/Footer.tsx, src/components/Navbar.tsx, src/tests/components/Navbar.test.tsx
Fix the Explore CTA Void on Nav to scroll to the footer.
- Change the scrolltoExplore -> scrolltoFooter for Explore button in Nav
- Made changes in testcase
https://github.com/user-attachments/assets/5173e03e-a6d6-4829-88a7-38c1f7c22eed
- Issue #106 
- Pull Request #<NUMBER>
- [] Vital features and changes captured in unit and/or integration tests
=> fix: scroll of Explore button to the footer

src/components/SampleDropdown.tsx
This PR fixes a critical issue in `SampleDropdown.tsx` where `samples.map(...)` would crash the UI if samples was undefined. The fix ensures that the dropdown gracefully handles the missing state by using optional chaining (`?.`) and a fallback (`|| []`).
1. Wrapped `samples.map(...)` in `samples?.map(...) || []` to prevent runtime crashes.
2. Ensured the dropdown renders an empty menu instead of breaking the application
=> Fix: Prevent UI Crash When `samples` is Undefined

package-lock.json, src/App.tsx, src/components/Footer.tsx, src/tests/components/__snapshots__/Footer.test.tsx.snap
-This PR improves the responsiveness and appearance of the footer to ensure a better user experience on different screen sizes.
-- Made the footer collapsible on smaller screens with a visible "Expand Footer" button.
- Ensured the footer sections are properly aligned in full-screen mode (left and right positioning).
-none
**Before**
**After**
https://github.com/user-attachments/assets/6c2e3d9a-51ac-4b7a-8509-5a99c7045d92
- Issue #133
=> feat(*): responsive footer for small screens - I133

src/components/FabButton.tsx
This PR resolves the overlapping issue between the footer social links and the floating help icon on larger screens by adjusting margins and positioning in the `fabButton` component.
- Updated the `fabButton` component to adjust margins and positioning.
**Before (Overlap):**  
https://github.com/user-attachments/assets/9bf02128-5c0c-48a0-93ed-efb15aa6ffe8
**After (Fixed):**  
https://github.com/user-attachments/assets/8fd44ea5-d4f9-4946-b35c-e332b4db74fa
- Issue #199
=> fix(footer): resolve overlapping help icon on large screens

src/components/ToggleDarkMode.tsx, src/styles/components/ToggleDarkMode.ts
Fixes an issue where clicking on the outer container of the dark mode toggle unintentionally triggers the mode change. Now, only direct clicks on the button will toggle dark mode.
- <ONE>Fixed event listener placement to ensure only button clicks trigger dark mode.
- <TWO>Updated the ToggleDarkMode.tsx component to prevent unintended toggling.
- <TWO>Improved accessibility and UX by making the toggle interaction more precise.
n/a
**BEFORE**
https://github.com/user-attachments/assets/e58fa142-0419-4e27-8be8-47fe835a3df7
**AFTER**
https://github.com/user-attachments/assets/a1be99ec-64bb-478a-8874-a2ce9b5a9527
- Issue #201
=> fix(button): fix dark mode toggle click - I201

src/AgreementHtml.tsx, src/App.tsx, src/components/FullScreenModal.tsx, src/components/Navbar.tsx, src/components/Sidebar.tsx, src/editors/ConcertoEditor.tsx, src/editors/MarkdownEditor.tsx
This PR resolves ESLint errors and TypeScript type declaration inconsistencies across multiple files to improve code quality, maintainability, and developer experience.
- Fixed ESLint errors in `Sidebar.tsx`, `FullScreenModal.tsx`, `Navbar.tsx`, `ToggleDarkMode.tsx`, `App.tsx`, `ConcertoEditor.tsx`, `MarkDownEditor.tsx`, and `AgreementHTML.tsx`.
- Resolved TypeScript type inconsistencies, missing types, and improper type assertions in the above files.
- Ensured all files adhere to the configured ESLint rules and TypeScript type safety standards.
- Some files required significant refactoring to resolve TypeScript type issues.
- ESLint rules were strictly enforced, which may require additional review to ensure no unintended side effects.
N/A (No UI changes were made; this PR focuses on code …
=> fix: resolve ESLint and TypeScript type declaration issues in multiple files

src/components/FabButton.tsx, src/styles/components/FabGlobalStyles.ts
- Adjusted the clickable area of the Floating Action Button (FAB) to match its visual boundary, preventing unintended activation when hovering near its padding area
- Ensure this change does not interfere with the button's appearance or other UI interactions.
- Verify that the hover effect still works as expected without triggering outside the button's visible area.
https://github.com/user-attachments/assets/22f5f7d9-c00b-4842-900b-767feee9d2c1
- Issue #242
=> The FAB floating button gets triggered when I am near to its padding area.

src/AgreementHtml.tsx, src/components/ToggleDarkMode.tsx, src/components/useUndoRedo.ts, src/editors/editorsContainer/AgreementData.tsx, src/editors/editorsContainer/TemplateMarkdown.tsx, src/editors/editorsContainer/TemplateModel.tsx
- Added **Undo** and **Redo** icons next to the editor headings in `AgreementData.tsx`, `TemplateMarkdown.tsx`, and `TemplateModel.tsx`.
- Implemented undo/redo functionality using `useUndoRedo.ts` for better state management.
- Styled the icons to have a **rectangular box shape with a grey background** for better visibility.
- Ensured all editor headings use the same `<h3>` tag for consistency.
- Issue #204
=> feat(editor): add undo redo icons to editor - I204

src/components/useUndoRedo.ts
This PR fixes the issue where selecting a sample from the dropdown did not update the TemplateMark, Concerto Model, and Preview Data sections. The problem was caused by improper state synchronization in the `useUndoRedo` hook.
- Updated `useUndoRedo` hook to properly handle `initialValue` updates from the store.
- Added a `useEffect` to ensure the editor state resets and updates correctly when a new sample is selected.
- Ensured that changes propagate to all dependent components.
https://github.com/user-attachments/assets/93e8db1b-e36b-44b7-9a0e-f805bf38e7fe
- Issue #317
=> fix(samples): update TemplateMark, Concerto Model, and Preview Data on selection

src/App.tsx, src/components/ToggleDarkMode.tsx
- <ONE>Reduced excessive whitespace by adjusting paddingBottom to 24px.
- <TWO>Improved layout proportionality between content and footer for a better user experience.
- <ONE>This is a minor UI fix and does not affect functionality.
- <TWO>No breaking changes introduced.
**BEFORE**
**AFTER**
- Issue #269
=> fix(whitespace): Reduce whitespace above footer - I269

src/AgreementHtml.tsx, src/editors/ConcertoEditor.tsx
This PR adds an automatic pairing feature for curly braces {} in the Concerto model section within the Monaco Editor. This improves the editing experience by reducing syntax errors and ensuring balanced brace structures.
- <ONE> Implemented auto-insertion of closing braces when an opening brace { is typed
- <ONE> Ensured proper indentation and cursor positioning for multi-line brace pairs
- <ONE> Supported nested brace structures in the Concerto model section
- <ONE> Prevented auto-pairing inside strings and comments
- <ONE> Added a configuration option to enable/disable this feature
After Changes 
https://github.com/user-attachments/assets/89bfdad9-87e8-4f2c-a033-7d876976e2e8
- Issue #280
it-works) for your commits using the `--signoff` option of git commit.
=> feat(editor): Add auto-pairing for curly braces in Concerto model 

src/components/Content.tsx, src/components/ToggleDarkMode.tsx, src/styles/components/Content.ts
Improves Code Snippet UI & Add Copy Button
- <ONE>Implemented bash-like styling for better code snippet visibility.
- <TWO>Added a copy button for code snippets to improve usability.
- <TWO>Replaced pixel-based styles with rem for better scalability.
- <TWO>Ensured alignment and consistency across the documentation.
n/a
- Issue #271
=> feat(module): improve-styling-for-bash-code-snippets

src/AgreementHtml.tsx, src/App.tsx, src/components/ResizableContainer.tsx, src/editors/ConcertoEditor.tsx
This PR implements a resizable editor and preview pane feature, similar to LeetCode's interface. Users can now adjust the width of the editor and preview panes by dragging a divider between them. The preferred pane sizes are saved in local storage, ensuring persistence across sessions.
- <ONE> Added a draggable divider between the editor and preview panes.
- <TWO> Implemented event listeners to track mouse movement and resize panes dynamically.
- <THREE> Stored pane size preferences in local storage for a consistent user experience.
- <FOUR> Ensured real-time updates to pane sizes during resizing.
After changes
https://github.com/user-attachments/assets/0310799e-de92-424a-ba45-b79bc8d46670
- Issue #234
=> feat(editor): add resizable editor/preview panes 

src/components/Footer.tsx
This PR ensures that all external links in the website footer under(About, Community, Project sections) open in a new tab to improve user experience and avoid users unintentionally navigating away from the playground.
- Added `target="_blank"` and `rel="noopener noreferrer"` to all external links in the footer.
- Verified proper navigation and tab opening behavior.
- Make sure to verify that all links are external and not intended to be internal navigation.
- This change affects only the footer component.
- Issue #352
=> fix(footer): open footer links in new tab for better UX

src/components/Navbar.tsx
- Made the navbar sticky for improved user experience on scroll.
- Updated the styles for better responsiveness across devices.
- Ensure that sticky behavior works well across different screen sizes.
- Double-check if the navbar overlaps any content on scroll in specific cases.
- Issue #365
- Pull Request #367
=> Implemented sticky navbar for persistent visibility during scroll

src/ai-assistant/activityTracker.ts, src/ai-assistant/autocompletion.ts, src/ai-assistant/chatRelay.ts, src/ai-assistant/prompts.ts, src/components/AIChatPanel.tsx, src/components/AIConfigPopup.tsx, src/components/PlaygroundSidebar.tsx, src/editors/ConcertoEditor.tsx, src/editors/JSONEditor.tsx, src/editors/MarkdownEditor.tsx, src/editors/editorsContainer/AgreementData.tsx, src/editors/editorsContainer/TemplateMarkdown.tsx, src/editors/editorsContainer/TemplateModel.tsx, src/pages/MainContainer.tsx, src/types/components/AIAssistant.types.ts
Functionality for inline AI suggestions inside code editors and dark mode support for AI Assistant.
- `autocompletion.ts` is the core that produces the suggestions.
- If the last LLM call is still being processed or if it's been less than 2 seconds since the last call, then another LLM call isn't made to make sure that LLMs are used conservatively and provide practical suggestions instead of intrusive completions one after the other.
- `activityTracker.ts` keeps track of timestamp of last user activity in the editors, this is used in `autocompletion.ts` to trigger the LLM call for inline suggestions if the user has been inactive for 1 second.
- Appropriate prompt has been added in `prompts.ts` to generate the suggestions.
- Auto-completion is registered before the editors mount.
- Inline …
=> feat: inline AI suggestions inside code editors
